name: mltools
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.6.2
  - numpy=1.23.5
  - pandas=1.5.1
  - ipykernel=6.17.1
  - python=3.8.13
  - scikit-learn=1.1.3
  - seaborn=0.12.1
  - pip=22.3.1
  - scipy=1.9.3
  - notebook=6.5.2
  - imbalanced-learn=0.9.1
  - pip:
    - jupyter-contrib-nbextensions==0.7.0
    - ipywidgets==8.0.2
    - tqdm==4.64.1
    - lightgbm==3.3.3
    - shap==0.41.0
    - pyarrow==10.0.0
    - catboost==1.1.1
    - xgboost==1.7.1